### ISSUE TITLE
Errorhandling (File access)

### ISSUE THREAD

**Issue by roseswe** [ncs-sniper/Lib.SHA3#3]
Better it would be setting the HASH to "" (empty) and/or settings Error variables.

Lib.SHA3 > ./testsha3  non-existing-file
File: non-existing-file
An unhandled exception occurred at $000000000040DAF6 :
EFOpenError : Unable to open file "non-existing-file"
  $000000000040DAF6
  $000000000040D847
  $0000000000402693
  $00000000004003EC

**Comment by ncs-sniper** [comment]
This behaviour is completely intentional - in my opinion, functions (which get called directly in code, not from some linked library, of course) should not catch and supress their own errors, but propagate them outside and it should be responsibility of the caller to react to them. It is done this way in RTL and I am writing all my code in this manner too.
Sure, it would be better to document it, but you have probably noticed there is almost no documentation anyway - I am not planning to write it in forseeable future.
So I suggest you call the function inside try-except block, as it should be anyway for functions which are accessing files.
